/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import javax.swing.table.DefaultTableModel;
import operaciones.ListaClientes;

/**
 *
 * @author espin
 */
public class FrmMostrarClientes extends javax.swing.JFrame {
    
    FrmRegistroClientes fc = new FrmRegistroClientes();
    ListaClientes lc = fc.getListaClientes();
    DefaultTableModel modelo = new DefaultTableModel();
    
    public FrmMostrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbAviones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 172, 45));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        cbAviones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boeing 737", "Airbus A320", "Boeing 777", "Airbus A330", "Boeing 767", "Airbus A350", "Embraer E-Jet", "Bombardier CRJ", "McDonnell Douglas MD-80", "Sukhoi Superjet 100" }));
        cbAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAvionesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("SELECCIONE EL AVIÓN A CONSULTAR:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(cbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void cbAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvionesActionPerformed
        ListaClientes aux = new ListaClientes();
        if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Boeing 737")){
            aux = lc.obtenerClientesPorAvion("Boeing 737");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Airbus A320")){
            aux = lc.obtenerClientesPorAvion("Airbus A320");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Boeing 777")){
            aux = lc.obtenerClientesPorAvion("Boeing 777");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Airbus A330")){
            aux = lc.obtenerClientesPorAvion("Airbus A330");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Boeing 767")){
            aux = lc.obtenerClientesPorAvion("Boeing 767");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Airbus A350")){
            aux = lc.obtenerClientesPorAvion("Airbus A350");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Embraer E-Jet")){
            aux = lc.obtenerClientesPorAvion("Embraer E-Jet");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Bombardier CRJ")){
            aux = lc.obtenerClientesPorAvion("Bombardier CRJ");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("McDonnell Douglas MD-80")){
            aux = lc.obtenerClientesPorAvion("McDonnell Douglas MD-80");
        }else if(cbAviones.getSelectedItem().toString().equalsIgnoreCase("Sukhoi Superjet 100")){
            aux = lc.obtenerClientesPorAvion("Sukhoi Superjet 100");
        }
        aux.mostrar(modelo);
    }//GEN-LAST:event_cbAvionesActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.setVisible(false);
        fc.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMostrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JComboBox<String> cbAviones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
