/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import entidades.*;
import logica.*;
import operaciones.*;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author RenzoF
 */
public class FrmRegistroClientes extends javax.swing.JFrame {
    DefaultComboBoxModel<String> model= new DefaultComboBoxModel<>();
    private JComboBox<String> comboBoxEmpleados;
    FrmRegistroEmpleados re = new FrmRegistroEmpleados(); 
    public static ListaClientes lc = new ListaClientes();
    ListaEmpleados le = re.getListaEmpleados();
    ListaAsientos la= new ListaAsientos();
    ListaAsientosAbordo laa = new ListaAsientosAbordo();        
    Pila pila = new Pila();
    private int costoPasaje;
    /**
     * Creates new form FrmRegistroClientes
     */
    public FrmRegistroClientes() {
        comboBoxEmpleados = new JComboBox<>();
        initComponents();
        setLocationRelativeTo(null);
        cargarNombresEmpleados();       
    }
    
    private void cargarNombresEmpleados(){
        String []nombresEmpleados = re.getListaEmpleados().obtenerNombresEmpleados();
        for(int i=0;i<re.getListaEmpleados().contar();i++){
            jComboBox1.addItem(nombresEmpleados[i]);
        }
    }
    
    public ListaClientes getListaClientes(){
        return lc;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbDestino = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNAsiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnAsignarID = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNombreAvion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidadMaletas = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        btnConsultarAsiento = new javax.swing.JButton();
        btnCalcularCostoMaletas = new javax.swing.JButton();
        btnCalcularCosto = new javax.swing.JButton();
        btnConsultarAsiento1 = new javax.swing.JButton();
        btnConsultarAsiento2 = new javax.swing.JButton();
        btnMostrarRutas = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnActualizarCliente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE CLIENTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 330, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("SELECCIONAR EMPLEADO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 270, 40));

        jComboBox1.setModel(model);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 30));

        jLabel4.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 300, 40));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DNI: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, 30));
        jPanel1.add(txtDniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 220, 30));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOMBRE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 90, 30));
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 220, 30));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DESTINO: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 90, 20));

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EE.UU", "CANADA", "REINO UNIDO", "ESPAÑA", "BRASIL", "FRANCIA", "ALEMANIA", "ITALIA", "JAPON", "AUSTRALIA" }));
        cbDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(cbDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 220, -1));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("N° ASIENTO: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 120, -1));

        txtNAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNAsientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 220, 30));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("COSTO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 90, 30));

        txtCosto.setEditable(false);
        jPanel1.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 220, 30));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 60, -1));

        txtID.setEditable(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 220, 30));

        btnAsignarID.setBackground(new java.awt.Color(204, 204, 255));
        btnAsignarID.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnAsignarID.setForeground(new java.awt.Color(0, 0, 0));
        btnAsignarID.setText("ASIGNAR ID");
        btnAsignarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsignarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 130, 30));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("NOMBRE DEL AVIÓN:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 170, 40));

        txtNombreAvion.setEditable(false);
        jPanel1.add(txtNombreAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 220, 30));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CANTIDAD DE MALETAS: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 200, 30));
        jPanel1.add(txtCantidadMaletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 220, 30));

        btnRegistrarCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnRegistrarCliente.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 14)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarCliente.setText("REGISTRAR");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 680, 190, 40));

        btnConsultarAsiento.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarAsiento.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnConsultarAsiento.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarAsiento.setText("CONSULTAR");
        btnConsultarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAsientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 130, 30));

        btnCalcularCostoMaletas.setBackground(new java.awt.Color(204, 204, 255));
        btnCalcularCostoMaletas.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnCalcularCostoMaletas.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularCostoMaletas.setText("CALCULAR");
        btnCalcularCostoMaletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostoMaletasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularCostoMaletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 130, 30));

        btnCalcularCosto.setBackground(new java.awt.Color(204, 204, 255));
        btnCalcularCosto.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnCalcularCosto.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularCosto.setText("CALCULAR");
        btnCalcularCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcularCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 130, 30));

        btnConsultarAsiento1.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarAsiento1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnConsultarAsiento1.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarAsiento1.setText("MOSTRAR CLIENTES");
        btnConsultarAsiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAsiento1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarAsiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 160, 30));

        btnConsultarAsiento2.setBackground(new java.awt.Color(204, 204, 255));
        btnConsultarAsiento2.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnConsultarAsiento2.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarAsiento2.setText("CONSULTAR CLIENTE");
        btnConsultarAsiento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAsiento2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarAsiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 160, 30));

        btnMostrarRutas.setBackground(new java.awt.Color(0, 204, 204));
        btnMostrarRutas.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 14)); // NOI18N
        btnMostrarRutas.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarRutas.setText("¡CONOCE LAS RUTAS QUE TENEMOS PARA USTED!");
        btnMostrarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRutasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrarRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 430, 50));

        btnActualizarCliente.setBackground(new java.awt.Color(204, 204, 255));
        btnActualizarCliente.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarCliente.setText("ACTUALIZAR CLIENTE");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, 30));

        btnAtras.setBackground(new java.awt.Color(255, 102, 102));
        btnAtras.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("ATRAS");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 770, 120, 40));

        btnActualizarCliente1.setBackground(new java.awt.Color(204, 0, 0));
        btnActualizarCliente1.setFont(new java.awt.Font("DejaVu Sans Mono", 1, 12)); // NOI18N
        btnActualizarCliente1.setForeground(new java.awt.Color(204, 255, 204));
        btnActualizarCliente1.setText("CANCELAR VUELO");
        btnActualizarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cbDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinoActionPerformed

    private void btnConsultarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAsientoActionPerformed
        la.agregarAsientosDisponibles();
    }//GEN-LAST:event_btnConsultarAsientoActionPerformed
    
    
    private Empleado obtenerEmpleadoPorNombre(String nombreEmpleado) {
        NodoEmpleado p = le.getInicio();
        while (p != null) {
            if (p.getInfo().getNombre().equals(nombreEmpleado)) {
                return p.getInfo();
            }
            p = p.getSgte();
        }
        return null;
    }
    
    
    private void btnCalcularCostoMaletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostoMaletasActionPerformed
        try{
            int montoTotal;
            int cantidad = Integer.parseInt(txtCantidadMaletas.getText());
            int monto = cantidad * 500;
            montoTotal = costoPasaje + monto;
            txtCosto.setText(String.valueOf(montoTotal));
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        }
    }//GEN-LAST:event_btnCalcularCostoMaletasActionPerformed

    private void btnCalcularCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostoActionPerformed
        int indice = cbDestino.getSelectedIndex();
        switch(indice){
            case 0 -> {
                //EEUU
                costoPasaje = 2800;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Boeing 737");
            }
            case 1 -> {
                //CANADA
                costoPasaje = 3200;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Airbus A320");
            }
            case 2 -> {
                //REINO UNIDO
                costoPasaje = 5700;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Boeing 777");
            }
            case 3 -> {
                //ESPAÑA
                costoPasaje = 3000;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Airbus A330");
            }
            case 4 -> {
                //BRASIL
                costoPasaje = 1500;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Boeing 767");
            }
            case 5 -> {
                //FRANCIA
                costoPasaje = 3400;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Airbus A350");
            }
            case 6 -> {
                //ALEMANIA
                costoPasaje = 4000;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Embraer E-Jet");
            }
            case 7 -> {
                //ITALIA
                costoPasaje = 4200;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Bombardier CRJ");
            }
            case 8 -> {
                //JAPON
                costoPasaje = 7000;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("McDonnell Douglas MD-80");
            }
            case 9 -> {
                //AUSTRALIA
                costoPasaje = 8000;
                txtCosto.setText(String.valueOf(costoPasaje));
                txtNombreAvion.setText("Sukhoi Superjet 100");
            }   
        }
                
    }//GEN-LAST:event_btnCalcularCostoActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        try{
            String nombre = txtNombreCliente.getText();
            String dni = txtDniCliente.getText();
            String destino = (String) cbDestino.getSelectedItem();
            int nAsiento = Integer.parseInt(txtNAsiento.getText());
            
            try{
                int numero = Integer.parseInt(txtNAsiento.getText());
                if(!la.contiene(numero)){
                    laa.eliminarAsientoAbordo(numero);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Escoja otro asiento por favor");
                }
                int costo = costoPasaje;
                String id = txtID.getText();
                String nombreAvion = txtNombreAvion.getText();
                int maletas = Integer.parseInt(txtCantidadMaletas.getText());
                String nombreEmpleado = jComboBox1.getSelectedItem().toString();
                Empleado empleadoSeleccionado = obtenerEmpleadoPorNombre(nombreEmpleado);
                if(empleadoSeleccionado!=null){
                    Cliente cliente = new Cliente(nombre, dni, destino, nAsiento, costo, id, nombreAvion, maletas);
                    empleadoSeleccionado.registrarCliente(cliente);
                    lc.InsertarFinal(cliente);
                    JOptionPane.showMessageDialog(null, "Muchas Gracias por su preferencia. ¡Feliz Vuelo Sr/a " + nombre+"!");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Seleccione un empleado válido");
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        }
        txtNombreCliente.setText("");
        txtDniCliente.setText("");
        txtNAsiento.setText("");
        txtID.setText("");
        txtCantidadMaletas.setText("");
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnAsignarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarIDActionPerformed
        Pila ids = new Pila();
        ids.agregarIds();
        if(!ids.empty()){
            String nuevoID = String.valueOf(ids.pop());
            txtID.setText(nuevoID);
        }
        else {
            // No hay más IDs disponibles
            JOptionPane.showMessageDialog(null, "No hay más IDs disponibles");
        }
    }//GEN-LAST:event_btnAsignarIDActionPerformed

    private void btnConsultarAsiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAsiento1ActionPerformed
        FrmMostrarClientes fmc = new FrmMostrarClientes();
        this.setVisible(false);
        fmc.setVisible(true);
    }//GEN-LAST:event_btnConsultarAsiento1ActionPerformed

    private void btnConsultarAsiento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAsiento2ActionPerformed
        String id = JOptionPane.showInputDialog(this,"Ingrese ID del cliente a consultar");
        if(lc.verificarID(id)){
            lc.Buscar(id);
        }
        else
            JOptionPane.showMessageDialog(null, "La id ingresada no pertenece a ningún usuario");
    }//GEN-LAST:event_btnConsultarAsiento2ActionPerformed

    private void txtNAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNAsientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNAsientoActionPerformed

    private void btnMostrarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRutasActionPerformed
        this.setVisible(false);
        FrmRutas frameRutas = new FrmRutas();
        frameRutas.setVisible(true);
    }//GEN-LAST:event_btnMostrarRutasActionPerformed

    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        this.setVisible(false);
        new FrmActualizarCliente(lc).setVisible(true);
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        new FrmRegistroEmpleados().setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnActualizarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCliente1ActionPerformed
        this.dispose();
        new FrmCancelacionVuelos(lc).setVisible(true);
    }//GEN-LAST:event_btnActualizarCliente1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnActualizarCliente1;
    private javax.swing.JButton btnAsignarID;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCalcularCosto;
    private javax.swing.JButton btnCalcularCostoMaletas;
    private javax.swing.JButton btnConsultarAsiento;
    private javax.swing.JButton btnConsultarAsiento1;
    private javax.swing.JButton btnConsultarAsiento2;
    private javax.swing.JButton btnMostrarRutas;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JComboBox<String> cbDestino;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidadMaletas;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNAsiento;
    private javax.swing.JTextField txtNombreAvion;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
